### ISSUE TITLE
代码无关的东西请滚出GitHub

### ISSUE THREAD

**Issue by CenJIl** [LGBT-CN/LGBTQIA-In-China#104]
什么时候github也变成了政治正确的舞台了？把中文给老子删了

**Comment by U-v-U** [comment]
CenJIl,

Hello. I hope you are safe and working well. Thanks for your attention to our project. We are grateful for your creative thinking in being able to ask questions.

Before answering your question I would like to know how you define something that is not code related, documentation, licenses or what? If they are all irrelevant, then I suggest that GitHub remove its document as well. Along your lines, 996.icu should also be reasonably removed.

Given that you have not sent any similar issue to 996.icu, I have reason to suspect that you are deliberately targeting our project. In other words you are a serious sexist. Shame on you.

If you have any questions, feel free to contact with us.

Regards,
Kevin

**Comment by U-v-U** [comment]
CenJIl,

Hello. I hope you are safe and working well. Thanks for your attention to our project. We are grateful for your creative thinking in being able to ask questions.

Before answering your question I would like to know how you define something that is not code related, documentation, licenses or what? If they are all irrelevant, then I suggest that GitHub remove its document as well. Along your lines, 996.icu should also be reasonably removed.

Given that you have not sent any similar issue to 996.icu, I have reason to suspect that you are deliberately targeting our project. In other words you are a serious sexist. Shame on you.

If you have any questions, feel free to contact with us.

Regards,
Kevin

**Comment by KevinZonda** [comment]
CenJIl,

Hello. I hope you are safe and working well. Thanks for your attention to our project. We are grateful for your creative thinking in being able to ask questions.

Before answering your question I would like to know how you define something that is not code related, documentation, licenses or what? If they are all irrelevant, then I suggest that GitHub remove its document as well. Along your lines, 996.icu should also be reasonably removed.

Given that you have not sent any similar issue to 996.icu, I have reason to suspect that you are deliberately targeting our project. In other words you are a serious sexist. Shame on you.

If you have any questions, feel free to contact with us.

Regards,
Kevin

**Comment by EpLiar** [comment]
Now, I see a monkey open this issue.

**Comment by AyagawaSeirin** [comment]
傻逼。

**Comment by CenJIl** [comment]
> CenJIl,
> 
> Hello. I hope you are safe and working well. Thanks for your attention to our project. We are grateful for your creative thinking in being able to ask questions.
> 
> Before answering your question I would like to know how you define something that is not code related, documentation, licenses or what? If they are all irrelevant, then I suggest that GitHub remove its document as well. Along your lines, 996.icu should also be reasonably removed.
> 
> Given that you have not sent any similar issue to 996.icu, I have reason to suspect that you are deliberately targeting our project. In other words you are a serious sexist. Shame on you.
> 
> If you have any questions, feel free to contact with us.
> 
> Regards,
> Kevin

**Comment by CenJIl** [comment]
> CenJIl,
> 
> Hello. I hope you are safe and working well. Thanks for your attention to our project. We are grateful for your creative thinking in being able to ask questions.
> 
> Before answering your question I would like to know how you define something that is not code related, documentation, licenses or what? If they are all irrelevant, then I suggest that GitHub remove its document as well. Along your lines, 996.icu should also be reasonably removed.
> 
> Given that you have not sent any similar issue to 996.icu, I have reason to suspect that you are deliberately targeting our project. In other words you are a serious sexist. Shame on you.
> 
> If you have any questions, feel free to contact with us.
> 
> Regards,
> Kevin

I did not pay any attention to it,PROJECT? Ridiculous.

How to define code related.I hava to say that most of documentations and licenses in GitHub are obviously related.Although  I  used to Followed 996.icu,it is low correlated.But at least it fight for programmer to work less hours.

As for it,I did not find any correlation between code and it.Can you imagine that,when you browse github after work.A Rainbow Flag laying in your page.Nice time was over before it had begun.I do hate the LGBT fighter,gays as i know most of them wants to live in a normal way like a  straight one rather than to be display.Are you straight?Can you feel gays' feeling?Do you have the right to decide how gays should be treated instead of themselvies?That is the reason why I make a disgusted issue of this.it deserves.Especially in github,a programming technology community.

**Comment by Mabbs** [comment]
Anyway, the repository doesn't violate GitHub's TOS, but what you do may violate GitHub's TOS.

**Comment by KevinZonda** [comment]
Hi @CenJIl,
Thank you so much for your reply.

Yes, I think LGBT-CN is a project. If you don't think it's a project, feel free to pull out your project and show us what you've done. Talk is cheap. Show us your code. If you don't have even one repository that exceeds the star count of the LGBT-CN project, I'm sorry for your incompetence. And I hope that you will be able to reach the star count of **non-project repository** in one day.
Regarding 996.icu, I support it. It is an excellent example of a *non-code related* repository.

For LGBT-CN, if you read our description carefully, we have described the applicable population –  programmers. Of course, if you cannot understand it, I apologise for the poor language support. Feel free to send a pull request to our [internationalisation repository](https://github.com/LGBT-CN/lgbt-cn.github.io/tree/master/kvm/data) to help us improve the document.

As for the rainbow flag, I think of it as a symbol. If you use any international social platform, then rainbow flags will be everywhere. If you can't see it, it can only demonstrates that you're too narrowly socialised or you don't have any friends. How sad and painful that is! I am deeply sorry if I have accidentally poked your poor heart out.

On the last point, I think you've mapped the LGBTQIA+ population uniformly to homosexuality. And you're using the wrong term. In other words, it's a reflection of inadequate knowledge, illiteracy, or lack of intelligence. To answer the question of whether I am gay or not. I will say that I am not a purely gay - I am pansexual. I deeply crashed on a boy. I think I know better than you what it feels like.

Thanks again for your reply. I hope you have a wonderful life.

KevinZonda
19/05/2021

**Comment by imkiva** [comment]
> 把中文给老子删了

![image](https://user-images.githubusercontent.com/9902643/118927994-336c9b80-b975-11eb-9d3f-4c84a910f47e.png)

You first?

> PROJECT? Ridiculous.

Same. All these 0-starred repos? **PROJECT? Ridiculous.**

**Comment by CoelWu** [comment]
Nonsense , Conceptual shift and Ridiculous.

**Comment by AkigawaRinko** [comment]
你个赖屁娃娃一天逼逼赖赖的，一天到晚原理主义是不是更方便你妈在天上飞呢？幼稚至极，捡到“政治正确”这么一个词简直要不完买不着了，就到处炫耀好凸显你比你两厘米金针菇还短的见识呢😅😅😅

**Comment by AkigawaRinko** [comment]
干正事干不来，看到LGBT条件反射起来贼他妈精神来了是吧😅😅
#中华男儿魅力时刻

**Comment by Borschts** [comment]
@AkigawaRinko 誰給你的面子替GitHub代言？沒違反TOS連GitHub也管不著，你以為你自己是誰？ಠ ͜ʖ ಠ
給你參考： https://docs.github.com/en/github/site-policy/github-terms-of-service

**Comment by EpLiar** [comment]
> @AkigawaRinko 誰給你的面子替GitHub代言？沒違反TOS連GitHub也管不著，你以為你自己是誰？ಠ ͜ʖ ಠ
> 
> 給你參考： https://docs.github.com/en/github/site-policy/github-terms-of-service

老哥是不是艾特错人了 (

**Comment by Borschts** [comment]
> > @AkigawaRinko 誰給你的面子替GitHub代言？沒違反TOS連GitHub也管不著，你以為你自己是誰？ಠ ͜ʖ ಠ
> > 給你參考： https://docs.github.com/en/github/site-policy/github-terms-of-service
> 
> 老哥是不是艾特错人了 (

我自裁（

**Comment by AkigawaRinko** [comment]
> @AkigawaRinko 誰給你的面子替GitHub代言？沒違反TOS連GitHub也管不著，你以為你自己是誰？ಠ ͜ʖ ಠ
> 給你參考： https://docs.github.com/en/github/site-policy/github-terms-of-service

姐，您好像真的艾特错人了

**Comment by Borschts** [comment]
> > @AkigawaRinko 誰給你的面子替GitHub代言？沒違反TOS連GitHub也管不著，你以為你自己是誰？ಠ ͜ʖ ಠ
> > 給你參考： https://docs.github.com/en/github/site-policy/github-terms-of-service
> 
> 姐，您好像真的艾特错人了

(☞ ಠ_ಠ)☞當沒看到（

**Comment by 1715173329** [comment]
> Now, I see a monkey open this issue.

tbh, I can't agree more.

**Comment by KevinZonda** [comment]
Close cuz it's nonsense and has been silented for days.

**Comment by zuorong-zhang-contributer** [comment]
@KevinZonda @kecrily please cancel pinned for this issue.

**Comment by kecrily** [comment]
> 
> 
> @KevinZonda @kecrily please cancel pinned for this issue.

Done.
