### ISSUE TITLE
讲三个笑话

### ISSUE THREAD

**Issue by FooFooDamon** [LGBT-CN/LGBTQIA-In-China#149]
讲三个笑话：中国古代蔡桓公说自己没病，当代欧美说自己是民主灯塔和硬刚新冠，现在又惊现gay试图把github变gayhub！

**Comment by AyagawaSeirin** [comment]
So? What's your problem?

**Comment by KevinZonda** [comment]
Wats ur problem?

**Comment by Cubik65536** [comment]
So? What's ur problem?

**Comment by lwd-temp** [comment]
这个仓库不违反任何EULA。即使您有异议，平台也不会干预。
This repository does not violate any EULA. Even if you have an objection, the platform will not intervene.
祝好运。
Good luck.

**Comment by hunaulys** [comment]
你们有一个误区：认为自己的想法一定是正确的，然后强加给不支持这种想法的人！

**Comment by Cubik65536** [comment]
> 你们有一个误区：认为自己的想法一定是正确的，然后强加给不支持这种想法的人！

这句话适用于两种人：
1. 支持LGBT+且强制要求所有人支持LGBT+的人
2. 不支持LGBT+且强制要求所有人不支持LGBT+，甚至觉得支持/作为LGBT+就该消失的人

本 org 没有强制任何人支持 LGBTQ+，任何人可以选择在此 repo 署名表达支持，任何人也可以选择直接忽略。同样的，我想一个人走到一个团体中然后大喊这就是个笑话然后被讨厌是正常的。现在，这个 issue 里，是谁在《认为自己的想法一定是正确的，然后强加给不支持这种想法的人》？

**Comment by AyagawaSeirin** [comment]
> 你们有一个误区：认为自己的想法一定是正确的，然后强加给不支持这种想法的人！

典中典之只要我“不公开歧视”就是对TA们最大的仁慈，同时要求“尊重我对LGBT的隐形歧视”
