### ISSUE TITLE
Move to organization?

### ISSUE THREAD

**Issue by KevinZonda** [LGBT-CN/LGBTQIA-in-China#16]
Found an organization, move this repo to the org may a good idea.

**Comment by scvoet** [comment]
Thank you for your advice. I am in charge of this project by myself. If I create an organization, would you like to join?

**Comment by KevinZonda** [comment]
> Thank you for your advice. I am in charge of this project by myself. If I create an organization, would you like to join?

of course yes

**Comment by scvoet** [comment]
> > Thank you for your advice. I am in charge of this project by myself. If I create an organization, would you like to join?
> 
> of course yes

I 'd finished it and invited you. But I think the org maybe don't have any things need us to do. Beside, are you join our telegram group? Maybe we can communicate it more in there.

**Comment by KevinZonda** [comment]
> > > Thank you for your advice. I am in charge of this project by myself. If I create an organization, would you like to join?
> > 
> > 
> > of course yes
> 
> I 'd finished it and invited you. But I think the org maybe don't have any things need us to do. Beside, are you join our telegram group? Maybe we can communicate it more in there.

yes, I will mention you at TG.
