### ISSUE TITLE
The website is crashed

### ISSUE THREAD

**Issue by Michael18811380328** [LGBT-CN/LGBTQIA-In-China#164]
The main page (https://lgbt-cn.org/) is crashed

**Comment by KevinZonda** [comment]
@kecrily

**Comment by CberYellowstone** [comment]
I misread the letter C at first glance, haha

**Comment by Michael18811380328** [comment]
I find the domain name resolution error (lgbt-cn.org)

**Comment by Michael18811380328** [comment]
ping: cannot resolve https://lgbt-cn.org/: Unknown host

**Comment by dishomeworker** [comment]
I think this is because the domain name registration has expired.

**Comment by KevinZonda** [comment]
hv no idea how to take back

**Comment by renpengben** [comment]
This organization is a porn site without a word. I got in from the people I follow 啊阿啊

**Comment by renpeng301** [comment]
牛逼 一个黄色网站组织啊

**Comment by nishidashabia** [comment]
dick in his ass?

**Comment by KevinZonda** [comment]
> dick in his ass?

Seriously?

**Comment by KevinZonda** [comment]
fall back to GH
