### ISSUE TITLE
fuck your freedom

### ISSUE THREAD

**Issue by fhtfc** [LGBT-CN/LGBTQIA-In-China#183]
最近几天LGBT运动在全球范围突然莫名其妙的就热起来了
有没有发现一个奇怪的现象，该项目构建者头像大部分都是二次元，这些只是巧合吗？。
中国尊重人权，中国不歧视LGBT，歧视的是各种主义，和打着这些主义旗号兴风作浪的群体。
像是女权、环保、动保、素食，甚至LGBT这些概念都是经不起推敲的，允许你们拥有自己的自由，允许你们存在，但不允许你们兴风作浪，望好自为之。

**Comment by KevinZonda** [comment]
Oh seriously?

**Comment by Restent** [comment]
> 最近几天LGBT运动在全球范围突然莫名其妙的就热起来了 有没有发现一个奇怪的现象，该项目构建者头像大部分都是二次元，这些只是巧合吗？。 中国尊重人权，中国不歧视LGBT，歧视的是各种主义，和打着这些主义旗号兴风作浪的群体。 像是女权、环保、动保、素食，甚至LGBT这些概念都是经不起推敲的，允许你们拥有自己的自由，允许你们存在，但不允许你们兴风作浪，望好自为之。

在你发布你自己的言论之前，我希望你能好好想想一些因素。

是的，大多数贡献者的头像都是二次元头像，但我真心不建议以一概全。我们都是支持 LGBT 的一份子，并且您说的 “不歧视 LGBT“ 已经存在有反例。如果后续出现与您言论相关的问题的话，后果由您一人承担。

我们用什么头像有我们自己的自由，我们有什么想法有我们自己的自由，与您无关。

如果您还是坚持您的狭隘想法的话，我给的建议是别来搜索，眼不见心不烦，谢谢。

**Comment by Restent** [comment]
另，您不配用 "Fuck" 这个单词。请检查其是否适用于您的身上。
