### ISSUE TITLE
域名是否出现问题？

### ISSUE THREAD

**Issue by Nofated095** [LGBT-CN/LGBTQIA-In-China#185]
如题 我在访问<https://lgbt-cn.org/>时发现目前此域名可能已经被恶意注册变成了黄色网站并且GitHub Pages的页面也会跳转到色情页面
我认为这很讽刺 🏳️‍🌈LGBT的官网居然跳转色情网站？是不是太....
希望可以及时更改或者撤出官网

**Comment by KevinZonda** [comment]
没续费，被人买了:(

**Comment by Nofated095** [comment]
也许可以通过 Vercel 或多种方式来继续宣传 LGBTQIA-CN 项目
也可以利用类似于 Docusaurus 和 VuePress 做出更具有阅读性的文档、网页
萝卜青菜，各有所爱，只是一些小建议
总之，~~先把主页的域名撤掉吧~~

**Comment by KevinZonda** [comment]
> 也许可以通过 Vercel 或多种方式来继续宣传 LGBTQIA-CN 项目 也可以利用类似于 Docusaurus 和 VuePress 做出更具有阅读性的文档、网页 萝卜青菜，各有所爱，只是一些小建议 总之，~先把主页的域名撤掉吧~

try again
