### ISSUE TITLE
请不要把性取向问题当成缺失自由的借口

### ISSUE THREAD

**Issue by chihai-chuck** [LGBT-CN/LGBTQIA-In-China#268]
性取向异常只是一种心理+生理的问题，但是如果把这种病态思维当成是对自由平等的追求，那么抑郁症患者是不是也可以抱团取暖去追求所谓的自由平等？精神分裂症是不是也可以打着消除偏见的口号去追求所谓的自由平等？

有心理疾病就要去治疗，而不是把自己伪装成弱势群体说这个社会排斥你，论追求自由平等的命题，同性恋比女权差远了。

大张旗鼓的大肆宣扬，只会让大家讨厌这个群体，本身性取向并不会造成多大的偏见，这些的偏见都是自己的惺惺作态引来的。

**Comment by SliverRiver327** [comment]
不是哥们，抑郁症真的要抱团去追求什么自由平等么，我可不这么觉得。

女权还是算了吧，还没至于到那种程度，21 世纪女性的地位已经上来很多了，这可不是 20 世纪。同性恋嘛，反正能见到的战场可能会稍微比女权更夸张一点。

性取向不会造成多大的偏见的话，感觉你这个想法还是片面了捏。如果你不能确定国内所有人都不会对性取向有特别大的偏见，那我无话可说。

**Comment by SliverRiver327** [comment]
各类心理问题，能遭到各类不平等对待，只是这个 “对待” 的发起方纯纯有病而已。实质上，不管有什么心理疾病，你仍然在正常情况下得到平等的对待，并且有相应的自由。

性取向没人在意我保留 **过于片面** 的意见。我不知道你的地区的群众是怎么想的，但是在我这边，涉及到 **同性恋** 可以说是少不了嬉笑和谩骂，歧视感不就一整个拉上来了么。

你这个排句在我没发第一个 comment 的时候我就觉得有那么一点好笑。当然，旁人确实没有权力插手你的看法，但其实在我看来，把性取向和心理疾病挂钩，真的是一个很好笑的行为。

**Comment by KevinZonda** [comment]
性取向不一致不是一个异常，也不是问题。
我认为需要强调社会关怀与包容，这是抑郁症等心理疾病还是性取向不一致等的人群所期望的。大家期望的是接纳，关怀。不希望的是偏见与歧视。

**Comment by KevinZonda** [comment]
No

**Comment by cdlaimin** [comment]
我歧视≠我歧视

**Comment by Mcayear** [comment]
我希望这不是特权组织。

I hope this is not a privileged organization.

**Comment by Mcayear** [comment]
性少数没有问题，但并不意味着你见个人就要声明自己是性少数。

回顾女性平等权益的运动，现在”我是个女生“这句话已然具有可观的特权效应。

**Comment by Mcayear** [comment]
旗帜应该明确我们都属于人类命运共同体理应不受偏见，而不是我是性少数你得宽待我。

**Comment by gxres042** [comment]
> 性少数没有问题，但并不意味着你见个人就要声明自己是性少数。
> 
> 回顾女性平等权益的运动，现在”我是个女生“这句话已然具有可观的特权效应。

“我是 MTF” 有可能等于 “我是个女生” （纠正性别理解

**Comment by gxres042** [comment]
> 旗帜应该明确我们都属于人类命运共同体理应不受偏见，而不是我是性少数你得宽待我。

说一句算是我主观的话吧
这一个仓库的出发点是你的第一句，而当今有一部分的人属于第二句
我自己没想过为什么，也很难去理解

**Comment by Mcayear** [comment]
> > 性少数没有问题，但并不意味着你见个人就要声明自己是性少数。
> > 回顾女性平等权益的运动，现在”我是个女生“这句话已然具有可观的特权效应。
> 
> “我是 MTF” 有 很大 可能等于 “我是个女生” （纠正性别理解

好的。我想请教一下如果生理性别女性，心理性别男性。但仍说这句话，该如何理解。

**Comment by alex3236** [comment]
如果我没理解错的话，这个项目的初衷应该是“平等”而不是“特权”。这意味着追求应该是“每个人都一样，只要社会不把人当异类就行”，而不是“因为我是这类群体而需要给我们更多权益”。那么看当今中国法律，除了婚姻以外，LGBT+ 群体与正常人接受的权利和义务无异。换句话说，在法律层面这方面没啥好改的，除了婚姻。更多应该改变的是教育层面和社会认知，但群众对此普遍接受度低，目前教材只在初中课本中隐晦地用两句话带过性别认同和相关歧视行为。这方面的努力需要潜移默化长期改进，我绝对不认可特立独行地在网上大肆宣扬自己的身份，与不接受的群众对线。
