### ISSUE TITLE
我仅尊重先天性的性少数群体，那种变态的，打着政治正确旗号的所谓性少数群体早日滚出中国

### ISSUE THREAD

**Issue by zelihole** [LGBT-CN/LGBTQIA-In-China#270]
所以你这个仓库想干啥

**Comment by YisuiDenghua** [comment]
> 所以你这个仓库想干啥

![image](https://github.com/LGBT-CN/LGBTQIA-In-China/assets/102890144/4c95719b-d01f-49af-b510-01b5a1e51c79)

管好你自己的事。

**Comment by YisuiDenghua** [comment]
另外，我重申一点。性少数（LGBT 等）属于心理问题，不属于政治问题。古人云：「君子和而不同，小人同而不和。」教育我们君子之间即便思想观念、行事方式不同，也应和睦相处。而你将一切问题归于政治，仇恨着那些你未曾见面的人。将这里所云的小人刻画得淋漓尽致。像你这种数典而忘祖，无知而无耻，自诩正义的同时又违背着君子之道的两面三刀之人，是不是更应该滚出中国呢？

**Comment by SliverRiver327** [comment]
张口闭口政治，没啥好说了的。

**Comment by XiaoMouz** [comment]
> # 对于未达到高中学业的、低于 15-16 岁的学生
> 建议你们上到高中好好学学思想政治必修四，尽管他在表述一种很老套的唯物主义。

请尊重基本的社区礼仪和 [本 Repo 的 Issue 规范](https://github.com/LGBT-CN/LGBTQIA-In-China/issues/186)

作为在象牙塔中的一员你无法感同身受地体会到每个人的经历与立场，在你理解一个团体之前请你噤声

**Comment by XiaoMouz** [comment]
> # 对于未达到高中学业的、低于 15-16 岁的学生 
> 建议你们上到高中好好学学思想政治必修四，尽管他在表述一种很老套的唯物主义。 
 
请尊重基本的社区礼仪和 本 Repo 的 Issue 规范 (https://github.com/LGBT-CN/LGBTQIA-In-China/issues/186) 
 
作为在象牙塔中的一员你无法感同身受地体会到每个人的经历与立场，在你理解一个团体之前请你噤声

**Comment by sheepbox8646** [comment]
请你不要再来毒害青年人，我会收集证据去公安机关举报你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月17日(周日) 晚上11:55
收件人: ***@***.***&gt;;
抄送: "Acbox ***@***.******@***.***&gt;;
主题: Re: [LGBT-CN/LGBTQIA-In-China] 我仅尊重先天性的性少数群体，那种变态的，打着政治正确旗号的所谓性少数群体早日滚出中国 (Issue #270)




  
对于未达到高中学业的、低于 15-16 岁的学生
 
建议你们上到高中好好学学思想政治必修四，尽管他在表述一种很老套的唯物主义。
  
请尊重基本的社区礼仪和 本 Repo 的 Issue 规范 (#186)
 
作为在象牙塔中的一员你无法感同身受地体会到每个人的经历与立场，在你理解一个团体之前请你噤声
