### ISSUE TITLE
私はMTFです

### ISSUE THREAD

**Issue by Golden114514** [LGBT-CN/LGBTQIA-In-China#292]
私は楊思辰です、私の親友の余美玲が先日mtfになったそうです、私もちょっと変わってきました、実はbydのは体精です、2メートルの身長です、砂糖を食べた後、直接謝懿と肩を併べて、腋の下の腋毛もいい香りがする、とてもいい匂いがする。ハルビン外国語中学のバスケットボールの試合の中で、偶然の間、余美玲は突然彼女の美しい普西を見て、私達はその時最高潮に達して、それから、彼女は始めて雌二醇を食べて、それから癌の余美玲を見て、私は直接彼女をripしました。それでね、私もエストラジオールを食べ始めました。美味しかったですね、食べて立ってくれましたね、mtfになってよかったですね、来周は姉妹とエッチできないですね。ああああああああ

**Comment by gxres042** [comment]
![image](https://github.com/LGBT-CN/LGBTQIA-In-China/assets/53113178/5eb084bf-eed0-48dc-9d44-f4bb9d3ce69a)

希望您不是在装眼瞎。

**Comment by Golden114514** [comment]
Byd誰問你了,我們木桶飯怎麼你了

**Comment by Golden114514** [comment]
誰問你了，你才是歧視罷，我們mtf就是這樣，怎麼了？！？

**Comment by Golden114514** [comment]
哈爾濱外國語中學周波實名支持

**Comment by Golden114514** [comment]
哈爾濱外國語中學貓力汗實名支持姐妹，給我看來像個挺立的大寄八啊

**Comment by gxres042** [comment]
> “都”字用得不好，不是所有人都是在色色，尽管有一部分人。 这个问题我曾经在 https://github.com/LGBT-CN/LGBTQIA-In-China/discussions/195 提出来。如果你在推特上关注了一些跨性别，那么你大概率会收到很大规模的跨圈消息，其中不少是包含一定的色情内容。 色情没有什么不好，只是性质不同。变成女性化（或男性化）的身体是很多跨性别群体朝思暮想的愿望，如果只是以自己身体为中心，或者以男女朋友身体为中心，我认为这样的色情完全可以理解，并且我们应该尊重他们发布的这些内容，尽管有时可能会引起部分人不适。 但问题在于“圆角”（圈内词，即援交），这方面确实存在一定问题，通过自己女性化（男性化）的身体赚取利润。可以理解很多人也是迫于无奈，极度缺少日常生活费或药品费用才不得不援交。我完全可以理解这种情况，但是因为国内大陆的法律体系，我认为在国内还是需要尽可能安分守己一点。 当然这样一提，就又回到国家社会和企业怎么做那块了，我相信如果真的做好了这种情况会发生得少很多。
> Source: [https://github.com/LGBT-CN/LGBTQIA-In-China/blob/master/post/%E4%BF%9D%E6%8A%A4%E8%B7%A8%E6%80%A7%E5%88%AB%E7%BE%A4%E4%BD%93%E4%B8%8D%E6%98%AF%E4%B8%80%E5%8F%A5%E7%A9%BA%E5%8F%A3%E5%8F%B7.md](https://github.com/LGBT-CN/LGBTQIA-In-China/blob/master/post/%E4%BF%9D%E6%8A%A4%E8%B7%A8%E6%80%A7%E5%88%AB%E7%BE%A4%E4%BD%93%E4%B8%8D%E6%98%AF%E4%B8%80%E5%8F%A5%E7%A9%BA%E5%8F%A3%E5%8F%B7.md)

**Comment by Golden114514** [comment]
我Golden river 是個哈批日隆包，清不到過張，日瘋倒癲的

**Comment by Golden114514** [comment]
我啊Golden river 啊，麻賣麻批啊哈麻批卡jer得批爆

**Comment by gxres042** [comment]
> 我啊Golden river 啊，麻賣麻批啊哈麻批卡jer得批爆

Señor, parece que usted es bastante polémico sobre MtF y sus objetivos.
Parece que le gusta usar idiomas extranjeros, así que usaré el español para comunicarme con usted en el próximo Tema.
No sabemos lo que usted está tratando de hacer mediante el registro de tantas cuentas, ni sabemos lo que estas personas de las que usted habla son trans o han hecho. Por lo que a mi respecta, lo que estás haciendo es probablemente similar al comportamiento de la gente de MtF que mencionas.
Como ya he dicho, las cosas objetivas no se pueden cambiar, y lo mismo ocurre con las cosas que ya han ocurrido. Ciertamente puedes sentir aversión por estas personas en privado, pero atacarnos y acosarnos en este contexto es posiblemente incorrecto por tu parte, y espero que tú, como estudiante de secundaria, puedas entenderlo claramente, y espero sinceramente que tu familia tenga la educación necesaria para enseñarte lo que te mereces.
Puedo entender que esto no es diferente al comportamiento de algunas personas en el pasado, después de todo, sigues siendo una persona atrapada en tu país sin acceso a las realidades del mundo, y no pareces saber por qué existe la comunidad LGBTQIA, sino que sólo intentas desacreditarla. Si fueras un estudiante de escuela, me temo que ya habrías causado bullying en la escuela. No me extraña que sea necesario operar en el anonimato.
