### ISSUE TITLE
喜歡我MtF鄒韋志博嗎

### ISSUE THREAD

**Issue by junhaoroy** [LGBT-CN/LGBTQIA-In-China#306]
希望您不要裝眼瞎，我就是上次的炸屎那個，我的名字其實叫夏雨欣（窮歐），鄒韋志博是我的小號，我很喜歡偷錢，還喜歡玩原神，刚才我诈尸的时候你有在偷偷的看
![Screenshot_2024-01-12-17-57-05-02_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/LGBT-CN/LGBTQIA-In-China/assets/156270117/2518812e-e63c-4f23-8f38-8c61c4554e70)

**Comment by junhaoroy** [comment]
我爱邓修

**Comment by junhaoroy** [comment]
邓公给我割了丫丫，开了个pussy

**Comment by gxres042** [comment]
唉你太吵了
