### ISSUE TITLE
@zelihole 同学你好。首先。请你管好你自己的事。你 GitHub 的仓库我看过了，代码质量并不高。你与其在这里管别人的事不如先把自己该学的东西学好。

### ISSUE THREAD

**Issue by Gr-1m** [LGBT-CN/LGBTQIA-In-China#344]
@zelihole 同学你好。首先。请你管好你自己的事。你 GitHub 的仓库我看过了，代码质量并不高。你与其在这里管别人的事不如先把自己该学的东西学好。

另外，我重申一点。性少数（LGBT 等）属于心理议题，不属于政治议题。我不知道你在这里举报「政治类」的原因的意义是什么。你还在 issue #270 声称要我们滚出中国。那么我在这里引用我在该 issue 下的原话：

古人云：「君子和而不同，小人同而不和。」教育我们君子之间即便思想观念、行事方式不同，也应和睦相处。而你将一切问题归于政治，仇恨着那些你未曾见面的人。将这里所云的小人刻画得淋漓尽致。你自己想想，像你这种狂妄而无礼，数典而忘祖，无知而无义，自诩正义的同时又违背着君子之道的两面三刀之人，是不是更应该滚出中国呢？

最后，请你谨言慎行。如果你继续做出这样涉及仇恨，歧视及人身攻击的行为。我将会把你的发言全部存档，并向你所在的学校举报。介时你可能会失去学籍，甚至被移送公安机关接受处罚。

_Originally posted by @YisuiDenghua in https://github.com/LGBT-CN/LGBTQIA-In-China/issues/186#issuecomment-1627598102_

**Comment by Gr-1m** [comment]
为什么你要攻击 "写代码人群" 这性少数群体?, 为什么你要攻击 "小人" 这种性少数群体?? 你的这种冒犯让我这种 "受不了别人冒犯"群体感受到了冒犯, 同时我也是"无脏话主义"的少数群体,

**Comment by gxres042** [comment]
我并不是很懂您提起这个 Issue 是想表达什么意义。

- 如果您是说 zelihole 的话，他已经被 block 了，我觉得围绕他的话题没有必要再延伸下去。
- 如果您对置顶 Issue 的内容有异议，在此提出即可。

**Comment by Gr-1m** [comment]
为什么要block zelihole而不是 @YisuiDenghua?

**Comment by Gr-1m** [comment]
我们"烂代码制造"和"小人" 的性少数群体就可以被歧视被攻击吗?

**Comment by gxres042** [comment]
#270

**Comment by gxres042** [comment]
至于 zelihole 为什么被 block，理由很简单。
https://github.com/YiSuiDengHua/zelihole

**Comment by Gr-1m** [comment]
那么你们为什么要攻击这个名为zelihole的性少数群体?

**Comment by gxres042** [comment]
> 那么你们为什么要攻击这个名为zelihole的性少数群体?

请问你又怎么证明他是性少数群体呢？

**Comment by gxres042** [comment]
![Screenshot_2024-08-02-00-20-00-736_com.github.android.jpg](https://github.com/user-attachments/assets/b5adfaf0-af8e-4284-ae97-5b4f719233b0)

按你这么说，zelihole 他自己居然变成了自己不想变成的样子，未免有点好笑。

以及，你不要觉得这个截图是抹黑他的，他自己的仓库下面还留有相关 commit：

![Screenshot_2024-08-02-00-22-20-927_com.android.chrome.jpg](https://github.com/user-attachments/assets/5d02b2ad-af3c-44af-8979-1ca8e3e8dc6b)

`git commit -m "sb"` ，现在是真的好笑了。

**Comment by gxres042** [comment]
![Screenshot_2024-08-02-00-20-00-736_com.github.android.jpg](https://github.com/user-attachments/assets/b5adfaf0-af8e-4284-ae97-5b4f719233b0)

按你这么说，zelihole 他自己居然变成了自己不想变成的样子，未免有点好笑。

以及，你不要觉得这个截图是抹黑他的，他自己的仓库下面还留有相关 commit：

![Screenshot_2024-08-02-00-22-20-927_com.android.chrome.jpg](https://github.com/user-attachments/assets/5d02b2ad-af3c-44af-8979-1ca8e3e8dc6b)

`git commit -m "sb"` ，现在是真的好笑了。

**Comment by gxres042** [comment]
以及我得好心奉告一句：在置顶的 Issue 里我已经明确说过 **对于异议，我的建议是带上能够辅佐你的异议的相关论据，就好比你在写一篇论文一样。**

而您现在提出异议却没有带上任何的论据。如果接下来仍是如此，我想这个对话也没有必要继续了，望您谅解。
