### ISSUE TITLE
建议建立 QQ 和 Slack 群组。

### ISSUE THREAD

**Issue by zrzjohn** [LGBT-CN/LGBTQIA-in-China#39]
目前这个项目只有 Telegram 群组，在中国需要翻墙，并且国内大多都是 QQ 和 Slack 。因此我建议建立 QQ 和 Slack 群组。
@KevinZonda @scvoet

**Comment by zrzjohn** [comment]
QQ 群组我已经建好了。
[点击此链接加入](https://jq.qq.com/?_wv=1027&k=ho0GkbML)

**Comment by KevinZonda** [comment]
i don't think it's a good idea.

**Comment by KevinZonda** [comment]
To prevent misleading, I deleted one of your comments.
