### ISSUE TITLE
不要bb了

### ISSUE THREAD

**Issue by axuplus** [LGBT-CN/LGBTQIA-in-China#46]
能不能别在github上搞这些事情了 要搞去其他的网站去搞好不好 等你妈的封了才会高兴是吧  还有到底谁歧视同性了？？？

**Comment by KevinZonda** [comment]
Thanks for your issue.

**Comment by AyagawaSeirin** [comment]
宁就事nmslese？
笑死我力，，，

**Comment by studentmain** [comment]
```bash
#如何封禁github
iptables -t nat -I INPUT --sport 443 -m string --string github --algo bm -j REJECT
```

**Comment by KevinZonda** [comment]
Calm down ladies and gentlemen.
Most LGBT is not illegal in China also, right? @axuplus 

Refer: https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BDLGBT%E6%9D%83%E7%9B%8A
Refer: http://news.sina.com.cn/c/2018-04-15/doc-ifzcyxmu8369869.shtml

**Comment by KevinZonda** [comment]
@axuplus And, if you have any further question, welcome to issue. :D

**Comment by AkigawaRinko** [comment]
> 能不能别在github上搞这些事情了 要搞去其他的网站去搞好不好 等你妈的封了才会高兴是吧 还有到底谁歧视同性了？？？

GitHub被封關我什麼事？你看不到事物的根源嗎？LGBT吃你家林檎了？幹你娘齁就你也配寫程式？

**Comment by ESUAdmin** [comment]
> 大家冷静点，别给GitHub引流！！
难道大家没发现Github渐渐的已经快连不上了吗
像这种危险的操作暴露给zf
只会增大gfw墙掉GitHub的可能性
建议截图传播完事，不要暴露地址

（复制别人的高雅言论）

**Comment by KevinZonda** [comment]
@ESUAdmin maybe you should also open an issue to shadowsocks and v2fly

**Comment by KevinZonda** [comment]
@ESUAdmin Reply to him :D

**Comment by KevinZonda** [comment]
@KevinZonda and some fucking stupid 法轮功 and also programthink

**Comment by KagurazakaHanabi** [comment]
> 还有到底谁歧视同性了？？？

请，https://www.sohu.com/a/257248192_759181

**Comment by Mashirl** [comment]
如果仅仅因为这个就可以把GitHub封掉，更可以进一步证明LGBT+群体的权益无法被保障，请停止发布反智言论。

**Comment by axuplus** [comment]
> > 能不能别在github上搞这些事情了 要搞去其他的网站去搞好不好 等你妈的封了才会高兴是吧 还有到底谁歧视同性了？？？
> 
> GitHub被封關我什麼事？你看不到事物的根源嗎？LGBT吃你家林檎了？幹你娘齁就你也配寫程式？
你是弱智儿吗？这他妈是一个搞技术的网站 不是搞平权的好吗 去gayhub啊 我并没有帮着谁讲话，你还"Github被封关我什么事",就你这个智商只配吃屎懂吗

**Comment by axuplus** [comment]
> > > 能不能别在github上搞这些事情了 要搞去其他的网站去搞好不好 等你妈的封了才会高兴是吧 还有到底谁歧视同性了？？？
> > 
> > 
> > GitHub被封關我什麼事？你看不到事物的根源嗎？LGBT吃你家林檎了？幹你娘齁就你也配寫程式？
> > 你是弱智儿吗？这他妈是一个搞技术的网站 不是搞平权的好吗 去gayhub啊 我并没有帮着谁讲话，你还"Github被封关我什么事",就你这个智商只配吃屎懂吗
我从头到尾讲过跟LGBT歧视有关的话题了？？哪种人在Github搞平权了？你也只配在背后叫唤了 傻逼

**Comment by axuplus** [comment]
> > 还有到底谁歧视同性了？？？
> 
> 请，https://www.sohu.com/a/257248192_759181

哪条法律规定了不能聘用同性的人？学校解聘去找律师有法院解决啊，那反过来想想，用人单位也有解聘的权利啊，就跟有些公司不聘用有纹身的不很正常，不要在这个上面搞的乌烟瘴气的行吗。

**Comment by AyagawaSeirin** [comment]
> And i do understand the feelings of LGBT people,but take the right way to do these things PLEASE!!!

LGBT的权益在中国并未得到广泛的支持也是不争的事实，谢谢。
And this is one of the right way.

**Comment by axuplus** [comment]
> > Calm down ladies and gentlemen.
> > Most LGBT is not illegal in China also, right? @axuplus
> > Refer: https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BDLGBT%E6%9D%83%E7%9B%8A
> > Refer: http://news.sina.com.cn/c/2018-04-15/doc-ifzcyxmu8369869.shtml
> 
> Yeah,getting married is not legal yet,but i don't see most other countries are not legal as well.
> 
> > LGBT
> 
> And i do understand the feelings of LGBT people,but take the right way to do these things PLEASE!!!

Anyway,delete this issue, i don't wanna talk about this to someone who's moron. and good luck for this.

**Comment by KevinZonda** [comment]
@axuplus Fuck you for your issue.

**Comment by AyagawaSeirin** [comment]
> > > Calm down ladies and gentlemen.
> > > Most LGBT is not illegal in China also, right? @axuplus
> > > Refer: https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BDLGBT%E6%9D%83%E7%9B%8A
> > > Refer: http://news.sina.com.cn/c/2018-04-15/doc-ifzcyxmu8369869.shtml
> > 
> > 
> > Yeah,getting married is not legal yet,but i don't see most other countries are not legal as well.
> > > LGBT
> > 
> > 
> > And i do understand the feelings of LGBT people,but take the right way to do these things PLEASE!!!
> 
> Anyway,delete this issue, i don't wanna talk about this to someone who's moron. and good luck for this.

这就怂了？删是不可能删的。

**Comment by Zikinn** [comment]
> > > Calm down ladies and gentlemen.
> 
> > > Most LGBT is not illegal in China also, right? @axuplus
> 
> > > Refer: https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BDLGBT%E6%9D%83%E7%9B%8A
> 
> > > Refer: http://news.sina.com.cn/c/2018-04-15/doc-ifzcyxmu8369869.shtml
> 
> > 
> 
> > Yeah,getting married is not legal yet,but i don't see most other countries are not legal as well.
> 
> > 
> 
> > > LGBT
> 
> > 
> 
> > And i do understand the feelings of LGBT people,but take the right way to do these things PLEASE!!!
> 
> 
> 
> Anyway,delete this issue, i don't wanna talk about this to someone who's moron. and good luck for this.

这就怂了？

**Comment by KevinZonda** [comment]
@axuplus refer: https://duxiaofa.baidu.com/detail?searchType=statute&from=wise_28231&originquery=%E5%8A%B3%E5%8A%A8%E6%B3%95

**Comment by axuplus** [comment]
> > And i do understand the feelings of LGBT people,but take the right way to do these things PLEASE!!!
> 
> LGBT的权益在中国并未得到广泛的支持也是不争的事实，谢谢。
> And this is one of the right way.

那明天组织起来抗议啊 只会在后面bb 还找不到正确的路子 傻逼

**Comment by scvoet** [comment]
> 能不能别在github上搞这些事情了 要搞去其他的网站去搞好不好 等你妈的封了才会高兴是吧 还有到底谁歧视同性了？？？

> **不在沉默中爆发，就在沉默中灭亡。** -- 鲁迅

**Comment by AyagawaSeirin** [comment]
> > > And i do understand the feelings of LGBT people,but take the right way to do these things PLEASE!!!
> > 
> > 
> > LGBT的权益在中国并未得到广泛的支持也是不争的事实，谢谢。
> > And this is one of the right way.
> 
> 那明天组织起来抗议啊 只会在后面bb 还找不到正确的路子 傻逼

有趣的言论，有趣到我觉得您在说话时并不会经过您聪明的大脑。

**Comment by KevinZonda** [comment]
@AyagawaSeirin correct one thing. He has no smart (which you defined) brain. But has a super brilliant brain.

**Comment by Zikinn** [comment]
@axuplus 或许你也可以去建议“Github do not ban as”删库（笑

**Comment by ESUAdmin** [comment]
求求各位正常人和升级人（请勿对号入座）少进行无意义的争论，俺的邮箱都被爆了，qqqxx

**Comment by BigCoke233** [comment]
账号变成 ghost 了，看来是拿小号来恶心人的，梳理一下他的言论吧：

> 能不能别在github上搞这些事情了 要搞去其他的网站去搞好不好 等你妈的封了才会高兴是吧

GitHub 曾经就被 gfw 墙过，我记得是在 2013 年，当时有一堆程序员抗议就又回来了（不过 gist 还是被墙着的，一些”敏感“的仓库也被屏蔽了）。同时，认为在 GitHub 上谈论 LGBT+ 会被”封“，也就是认为 LGBT+ 是像”轮子“、programthink 那样的东西，这还不是歧视？

>> GitHub被封關我什麼事？你看不到事物的根源嗎？LGBT吃你家林檎了？幹你娘齁就你也配寫程式？
> 你是弱智儿吗？这他妈是一个搞技术的网站 不是搞平权的好吗 去gayhub啊 我并没有帮着谁讲话，你还"Github被封关我什么事",就你这个智商只配吃屎懂吗

弱智儿这样既冒犯别人又冒犯残障人士的词汇能在这种场合说出来，我已经对他没抱什么希望了。另外，他回复的这个叫做 AkigawaRinko 的人，从 TA 使用繁体字和「程式」这样的词汇就已经可以看出来他是台湾那边的了，大陆封杀 GitHub 跟 TA 的确没什么关系（

> Yeah,getting married is not legal yet,but i don't see most other countries are not legal as well.
>> LGBT
> And i do understand the feelings of LGBT people,but take the right way to do these things PLEASE!!!

第一句貌似有些表意上的问题，而且有些过于中式，我就当作是 ta 过于激动而表述有误了吧，他想表达的意思应该是「Yes, same-sex marriage is not legal (in China) yet. But in my view, it's illegal in most countries in the world as well.」。他说「i do understand the feelings of LGBT people」，如果这是真的，他就不会说出「在 github 宣扬 LGBT 平权会让 github 被中国大陆封禁」这样的话。

> 那明天组织起来抗议啊 只会在后面bb 还找不到正确的路子 傻逼

抗议怕不是什么正确的路子，游行倒还说得通。中华人名共和国宪法规定，人民有游行示威的权利，但：
根据《中华人民共和国游行示威法》第六条、第七条规定，向游行地公安机关申请；游行途经两市县的，向两地公安机关共同的上一级公安机关申请。
是的，这是要申请批准的，我想在现在的中国进行 LGBT+ 平权游行，怕是通过不了。
所以，你说的正确的路子呢，傻逼？

> 哪条法律规定了不能聘用同性的人？学校解聘去找律师有法院解决啊，那反过来想想，用人单位也有解聘的权利啊，就跟有些公司不聘用有纹身的不很正常，不要在这个上面搞的乌烟瘴气的行吗。

学校解聘同性恋教师可能不合法，但这也证明了歧视 LGBT+ 群体的人不在少数，并且还广泛地存在于教育体系中，这时候把法律拿出来说是就是在偷换概念。之后还说出”用人单位也有解聘的权利啊，就跟有些公司不聘用有纹身的不很正常“这种自相矛盾的话（顺带一提，都什么年代了还有人歧视纹身

---

我就是想从尽量客观的角度谈谈他的言论有多么愚蠢，这些话也不是说给他听的，他都删号了也没意义x

**Comment by KevinZonda** [comment]
@BigCoke233 准确来说，法律其实更能看出解雇行为本身的不合理。。。

**Comment by scvoet** [comment]
我们永远纪念着变相歧视性少数的 @auxplus 用户

**Comment by studentmain** [comment]
> 求求各位正常人和升级人（请勿对号入座）少进行无意义的争论，俺的邮箱都被爆了，qqqxx

仅仅是提醒一下，github有unsubscribe一个issue的功能，作为一个迫真社交平台，它这方面功能还是不错。

**Comment by AkigawaRinko** [comment]
> > > 能不能别在github上搞这些事情了 要搞去其他的网站去搞好不好 等你妈的封了才会高兴是吧 还有到底谁歧视同性了？？？
> > 
> > 
> > GitHub被封關我什麼事？你看不到事物的根源嗎？LGBT吃你家林檎了？幹你娘齁就你也配寫程式？
> > 你是弱智儿吗？这他妈是一个搞技术的网站 不是搞平权的好吗 去gayhub啊 我并没有帮着谁讲话，你还"Github被封关我什么事",就你这个智商只配吃屎懂吗

幹你娘齁GitHub是線上協作平台！GitHub只能用來寫程式嗎？原理主義者去死吧你？你自己上不去GitHub該怪你們自己管理網路的人，搞清楚不是我們把GitHub封鎖掉的，搞清楚本源好嗎？靠北喔。滾回牆裡不要翻牆行不行？

**Comment by AkigawaRinko** [comment]
我看真是跪久了站不起來了

**Comment by zrzjohn** [comment]
> 我看真是跪久了站不起來了

台湾人？

**Comment by 6324ccc** [comment]
> 能不能别在github上搞这些事情了 要搞去其他的网站去搞好不好 等你妈的封了才会高兴是吧 还有到底谁歧视同性了？？？

Nmslnese就这？

**Comment by KevinZonda** [comment]
@6324ccc 淡定了啦~

**Comment by zrzjohn** [comment]
@KevinZonda Please cancel "Pinned issues" for this issue.

**Comment by scvoet** [comment]
@zrzjohn I had unpinned it.
