### ISSUE TITLE
关于几点建议

### ISSUE THREAD

**Issue by zouyu0008** [LGBT-CN/LGBTQIA-In-China#49]
1.同性恋在中国并没有什么严重的迫害，有些人会歧视，但是并不多，当然主要歧视男同比较多。
2.虽然GitHub是全球最大的同性网站，玩笑的说，但是主要是code的分享，如果自己建站会更自由，这里可以只作为宣传网站的地方。据我所知，国内不会因为是同性恋网站就封站，当然极端言论和色情例外。
3.最后希望大家能理解同性恋，减少对他们的歧视。

**Comment by KevinZonda** [comment]
我很认同你的观点，👍

**Comment by zrzjohn** [comment]
> 我很认同你的观点，
你终于说中文了。

**Comment by zrzjohn** [comment]
> 我很认同你的观点，

你终于说中文了。

**Comment by Ernest111111** [comment]
还不太会建网站，打算现在GitHub写写文章
