### ISSUE TITLE
明确 README 中文章表格的版权申明

### ISSUE THREAD

**Issue by scvoet** [LGBT-CN/LGBTQIA-in-China#67]
README.md 中收录整理的文章应明确申明版权，以便其他人清楚是否允许转载、演绎。

现收录的三篇文章中《跨性别群体诸多权益应得到广泛关注》因其作者属于中国妇女报-刘明辉，根据《中华人民共和国著作权法》。其属于时事新闻，属于[公有领域](https://zh.wikipedia.org/wiki/公有领域)。

而由 Eltrac Koalar 创作的《刻板印象与 LGBT+ 平权》和《为什么人们讨厌同性恋》并未明确声明版权协议。其原文链接中底部的”All rights reserved.“和单独页面中的[说明](https://blog.guhub.cn/notice.html)存在冲突。希望 @BigCoke233  能够明确声明版权协议。

**Comment by BigCoke233** [comment]
已删除网站页脚的 All rights reserved 字样，版权协议请以说明页面为准

**Comment by KevinZonda** [comment]
Refer: a466783319301fcb756d47123445c2386d351764, 71c24eacc33f44b0be226ab2c1757e46115a2531
