### ISSUE TITLE
Separate website from master branch

### ISSUE THREAD

**Issue by KevinZonda** [LGBT-CN/LGBTQIA-In-China#93]
Given that we may need to split our i18 resources, it may be difficult for us to use Master as a GitHub Pages branch. We should probably create an lgbt-cn.github.io or similar thing (e.g., branch or repository) to handle content including translations.

考虑到我们可能需要拆分i18资源，所以我们也许很难使用Master作为GitHub Pages分支。我们也许应该创建一个 lgbt-cn.github.io 或者类似产物（包括分支或存储库）进行处理包括翻译在内的内容。

/cc @scvoet @studentmain

**Comment by KevinZonda** [comment]
Data of website is available at <https://github.com/LGBT-CN/Kvm/tree/master/Data>.

整理好的网站数据可以在 <https://github.com/LGBT-CN/Kvm/tree/master/Data> 找到。

**Comment by scvoet** [comment]
> Data of website is available at <https://github.com/LGBT-CN/Kvm/tree/master/Data>.
> 
> 整理好的网站数据可以在 <https://github.com/LGBT-CN/Kvm/tree/master/Data> 找到。

`data` 语言代码有问题。
- ~~`zh` `tw`~~
- `zh-hans` `zh-hant`

**Comment by KevinZonda** [comment]
Don't be so serious. It's just a sample. :)

26 Apr 2021, 12:32 by ***@***.***:

**Comment by KevinZonda** [comment]
Also, do u think it is necessary to migrate to Kvm? If yes, we should do it right now

26 Apr 2021, 12:32 by ***@***.***:

**Comment by scvoet** [comment]
@KevinZonda 渲染出的网页是什么样的。Need a demo

**Comment by KevinZonda** [comment]
the same as current one, it will generate the page based on model. Model is at here: <https://github.com/LGBT-CN/Kvm/blob/master/Data/model/index.kvm>

26 Apr 2021, 12:37 by ***@***.***:

**Comment by scvoet** [comment]
@KevinZonda ok, we can do it right  now

**Comment by KevinZonda** [comment]
Cool

26 Apr 2021, 12:43 by ***@***.***:

**Comment by KevinZonda** [comment]
@scvoet sorry percy, I found that we haven't decided that wether we need to separate the website from the master. So we cannot do migrate right now. I'll be appreciated that if you could decide it for me so that we can start working asap.

**Comment by KevinZonda** [comment]
Kvm's CI has been done. See https://github.com/LGBT-CN/Kvm/commit/d1c358a98fc2f900f2ed8f17c0cffc3dd3e310ce .
Generated files can be accessed at artifact.

**Comment by KevinZonda** [comment]
done in 7b74e699f6a93ab75107ddcc53a6233a9508696b
