### ISSUE TITLE
Japanese translation content issue

### ISSUE THREAD

**Issue by KevinZonda** [LGBT-CN/LGBTQIA-In-China#96]
Signature and article part shouldn't be placed at Japanese. Or, we should put in all translation part.

![image](https://user-images.githubusercontent.com/33132228/116102018-3b9f2700-a6a6-11eb-9952-a149688a6fcc.png)

Influence file: https://github.com/LGBT-CN/LGBTQIA-In-China/blob/master/README/ja-JP.md

**Comment by Michael18811380328** [comment]
This PR https://github.com/LGBT-CN/LGBTQIA-In-China/pull/97 will repair this issue soon.

**Comment by KevinZonda** [comment]
fix at 3a64423
